---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: vault-test
    app.kubernetes.io/managed-by: helm
data:
  SKIP_SETCAP: "1"
  VAULT_DEV_ROOT_TOKEN_ID: "{{ .Values.devRootTokenId }}"
