apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: vault
    app.kubernetes.io/managed-by: helm
data:
  VAK_VAULT_HOST: "{{ .Values.vaultHost }}"
  VAK_VAULT_MOUNT: "{{ .Values.vaultMount }}"
