---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-roles
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: vault-test
    app.kubernetes.io/managed-by: helm
data:
  default: |-
    {
      "bound_service_account_names": ["vault-agent-injector", "default"],
      "bound_service_account_namespaces": ["kube-system", "default"],
      "token_policies": ["test"]
    }
  test: |-
    {
      "bound_service_account_names": ["vault-agent-injector"],
      "bound_service_account_namespaces": ["kube-system"],
      "token_policies": ["test", "default"]
    }
