---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-kubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: vault-test
    app.kubernetes.io/managed-by: helm
data:
  VAK_VAULT_ROLE_ID: {{ .Values.vaultRoleId }}
  VAK_VAULT_SECRET_ID: {{ .Values.vaultSecretId }}
